-- Insert sample data into C2O_CONTRACT
INSERT INTO C2O_CONTRACT (CONTRACT_ID, ROOT_CONTRACT_ID, VERSION_NUMBER, LOCKED_BY, CONTRACT_STATUS, CREATED_DATE, MODIFIED_DATE)
VALUES (101, 100, 1, NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO C2O_CONTRACT (CONTRACT_ID, ROOT_CONTRACT_ID, VERSION_NUMBER, LOCKED_BY, CONTRACT_STATUS, CREATED_DATE, MODIFIED_DATE)
VALUES (102, 100, 2, NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO C2O_CONTRACT (CONTRACT_ID, ROOT_CONTRACT_ID, VERSION_NUMBER, LOCKED_BY, CONTRACT_STATUS, CREATED_DATE, MODIFIED_DATE)
VALUES (103, 200, 1, 'USER1', 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO C2O_CONTRACT (CONTRACT_ID, ROOT_CONTRACT_ID, VERSION_NUMBER, LOCKED_BY, CONTRACT_STATUS, CREATED_DATE, MODIFIED_DATE)
VALUES (104, 300, 1, NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Insert sample data into C2O_API_REQUEST
-- Queued requests with status 318
INSERT INTO C2O_API_REQUEST (REQUEST_ID, SOURCE_SYSTEM_ID, REQUEST_TYPE, REQUEST_STATUS, BASE_CONTRACT_ID, CREATED_DATE, MODIFIED_DATE)
VALUES (1001, 'SFDC', 'MIRROR_FFID', '318', 102, DATEADD('SECOND', -60, CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP());

INSERT INTO C2O_API_REQUEST (REQUEST_ID, SOURCE_SYSTEM_ID, REQUEST_TYPE, REQUEST_STATUS, BASE_CONTRACT_ID, CREATED_DATE, MODIFIED_DATE)
VALUES (1002, 'SFDC', 'MIRROR_FFID', '318', 102, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO C2O_API_REQUEST (REQUEST_ID, SOURCE_SYSTEM_ID, REQUEST_TYPE, REQUEST_STATUS, BASE_CONTRACT_ID, CREATED_DATE, MODIFIED_DATE)
VALUES (1003, 'SFDC', 'MIRROR_FFID', '318', 103, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO C2O_API_REQUEST (REQUEST_ID, SOURCE_SYSTEM_ID, REQUEST_TYPE, REQUEST_STATUS, BASE_CONTRACT_ID, CREATED_DATE, MODIFIED_DATE)
VALUES (1004, 'SFDC', 'MIRROR_FFID', '318', 104, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Non-queued requests
INSERT INTO C2O_API_REQUEST (REQUEST_ID, SOURCE_SYSTEM_ID, REQUEST_TYPE, REQUEST_STATUS, BASE_CONTRACT_ID, CREATED_DATE, MODIFIED_DATE)
VALUES (1005, 'SFDC', 'MIRROR_FFID', '319', 102, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
