-- Create C2O_CONTRACT table
CREATE TABLE C2O_CONTRACT (
    CONTRACT_ID NUMBER PRIMARY KEY,
    ROOT_CONTRACT_ID NUMBER,
    VERSION_NUMBER NUMBER,
    LOCKED_BY VARCHAR2(50),
    CONTRACT_STATUS VARCHAR2(10),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

-- Create C2O_API_REQUEST table
CREATE TABLE C2O_API_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    SOURCE_SYSTEM_ID VARCHAR2(50),
    CORELATION_ID VARCHAR2(50),
    REQUEST_PAYLOAD CLOB,
    REQUEST_STATUS NUMBER,
    CONTRACT_ID NUMBER,
    CONTRACT_TYPE VARCHAR2(50),
    LE_EFX_ID NUMBER,
    BILLING_SOURCE VARCHAR2(50),
    BUSINESS_UNIT VARCHAR2(10),
    CREATED_DATE TIMESTAMP(6),
    LAST_UPDATED_DATE TIMESTAMP(6),
    RESPONSE_PAYLOAD CLOB,
    HEADER_PAYLOAD CLOB,
    RESPONSE_SENT VARCHAR2(1),
    REQUEST_PAYLOAD2 CLOB,
    REQUEST_TYPE VARCHAR2(50),
    BASE_CONTRACT_ID NUMBER,
    RESPONSE_SENT_ON TIMESTAMP(6),
    REDRIVE_FLAG VARCHAR2(1),
    CASE_ID VARCHAR2(100),
    ORDER_ID NUMBER,
    SOURCE_ACK VARCHAR2(2),
    SOURCE_ACK_TIME TIMESTAMP(6),
    SOURCE_ACK_ID VARCHAR2(50),
    EVENT_ID VARCHAR2(100),
    CLOSED VARCHAR2(1),
    CLOSED_ON TIMESTAMP(6),
    QUEUED_PROCESSING_FLAG VARCHAR2(1),
    SOURCE_REQUEST_ID VARCHAR2(100),
    SOURCE_FFID VARCHAR2(100)
);

-- Create C2O_MP_LOG_MESSAGE table
CREATE TABLE C2O_MP_LOG_MESSAGE (
    LOG_MESSAGE_ID NUMBER PRIMARY KEY,
    MESSAGE_ID VARCHAR2(100) NOT NULL,
    BATCH_ID NUMBER,
    COMPONENT_NM VARCHAR2(50),
    LOG_MESSAGE CLOB,
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    LAST_UPDATED_ON TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(50),
    MESSAGE_TYPE VARCHAR2(20),
    ATTRIBUTE1 VARCHAR2(100)
);

-- Create sequence for LOG_MESSAGE_ID
CREATE SEQUENCE C2O_MP_LOG_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create C2O_MP_QUEUE_MESSAGE table
CREATE TABLE C2O_MP_QUEUE_MESSAGE (
    MESSAGE_ID VARCHAR2(100) PRIMARY KEY,
    BATCH_ID NUMBER NOT NULL,
    MESSAGE_STATUS NUMBER,
    QUEUE_MESSAGE CLOB,
    PRODUCER VARCHAR2(100),
    DESTINATION_QUEUE VARCHAR2(200),
    REPLAYED_ON TIMESTAMP,
    REPLAYED_BY VARCHAR2(50),
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    MESSAGE_LOG_LEVEL VARCHAR2(5) NOT NULL,
    ATTRIBUTE1 VARCHAR2(100)
);
